### PR TITLE
Feature add restaurant

### PR DESCRIPTION
**Pull request by carolCase**
added restauranr txt file

### CODE REVIEW

**Review by Clemond — COMMENTED** [review]
Please dont forget to save :D

**Review by hampus-code — COMMENTED** [review]
Please add something in the file.

**Review by ahmadardal — COMMENTED** [review]
It would be nice if the information was more structured. Add like a headline for each restaurant. Also please give meaningful names to your commits

**Review by hampus-code — APPROVED** [review]
Now it looks good

**Review by ahmadardal — COMMENTED** [review]
I don't understand, is it restaurants or fotball teams? 😂

**Review by Clemond — APPROVED** [review]

**Review by ahmadardal — APPROVED** [review]
Nice

**Pull request merged**
